import Head from 'next/head';
import styles from '../styles/Header.module.css';
import Header from '../component/header/Header';
import Title from '../component/main/Title';
import AboutUs from '../component/main/AboutUs';
import ProgrammingTechnologies from '../component/main/ProgrammingTechnologies';
import Steps from '../component/main/Steps';
import FAQ from '../component/main/FAQ';
import Review from '../component/main/Review';
import Gallery from '../component/main/Gallery';
import ContactUs from '../component/main/ContactUs';
import Footer from '../component/footer/Footer';
import BlurCircles from '../component/BlurCircles';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.container}>
        <BlurCircles />
        <Title />
        <AboutUs />
        <ProgrammingTechnologies />
        <Steps />
        <FAQ />
        <Review />
        <Gallery />
        <ContactUs />
      </main>
      <Footer />
    </>
  );
}
